services:
  - type: web
    name: ml-algorithm-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    buildFilter:
      paths:
        - backend/**

  - type: web
    name: ml-algorithm-learning
    runtime: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_BASE_URL
        sync: false
    buildFilter:
      paths:
        - frontend/**
