export const reportInsights = {
  0: {
    output: '連續數值',
    core: '線性迴歸用一條直線、平面或高維超平面近似特徵與目標值的關係。訓練時會尋找一組係數，讓預測值與真實值的整體誤差最小。',
    workflow: ['確認目標是連續數值', '檢查離群值與資料洩漏', '觀察特徵是否適合線性組合', '用 MAE、RMSE、R-squared 與殘差圖評估'],
    metrics: ['MAE', 'RMSE', 'R-squared', '殘差圖'],
    pitfalls: ['明顯非線性關係會低估或高估重要區間', '離群值會強烈影響係數', '多重共線性會讓係數解讀失真', '只看 R-squared 容易忽略系統性殘差'],
    practice: '收集廣告費、網站流量、業務拜訪數與歷史營收，建立下季營收預測模型，再檢查旺季殘差是否偏大。',
  },
  1: {
    output: '類別機率',
    core: '邏輯斯迴歸先計算線性分數，再用 sigmoid 函數轉成 0 到 1 的機率，常用於二元分類與風險分數。',
    workflow: ['確認目標是分類標籤', '處理類別不平衡', '標準化或編碼特徵', '依業務成本調整分類閾值'],
    metrics: ['Precision', 'Recall', 'F1-score', 'ROC-AUC', 'PR-AUC'],
    pitfalls: ['accuracy 在類別不平衡時可能誤導', '分類邊界偏線性', '閾值 0.5 不一定符合業務成本', '機率校準不足會影響風險判斷'],
    practice: '用登入次數、影片觀看比例、作業提交率與討論區發言，預測學生是否會完成線上課程。',
  },
  2: {
    output: '類別或數值',
    core: '決策樹透過一連串 if-else 條件切分資料，每個節點都嘗試讓子節點更純，最後形成可解釋的規則。',
    workflow: ['選擇可被切分的特徵', '用 Gini、entropy 或 MSE 衡量切分品質', '限制樹深與葉節點樣本數', '檢查規則是否符合領域知識'],
    metrics: ['Accuracy', 'F1-score', 'Gini impurity', 'Entropy', 'MSE'],
    pitfalls: ['樹太深容易記住雜訊', '資料小變動可能造成樹結構大變動', '單棵樹準確度常不如集成模型', '過度解讀偶然切分規則'],
    practice: '用收入、信用分數、負債比與逾期紀錄，建立貸款違約判斷規則，並限制最大深度方便解釋。',
  },
  3: {
    output: '類別或數值',
    core: '隨機森林把多棵決策樹組合起來，透過 bootstrap 抽樣與隨機特徵選擇降低單棵樹過擬合的風險。',
    workflow: ['準備多個有效特徵', '設定樹的數量與深度限制', '使用袋外資料或驗證集評估', '檢視特徵重要度但避免過度解讀'],
    metrics: ['Accuracy', 'F1-score', 'ROC-AUC', 'RMSE', 'Feature importance'],
    pitfalls: ['比單棵樹更難解釋', '訓練與預測成本較高', '特徵重要度可能偏向高基數特徵', '資料洩漏仍會讓表現虛高'],
    practice: '用血壓、膽固醇、年齡、BMI 與家族史預測疾病風險，再比較前幾名重要特徵。',
  },
  4: {
    output: '類別或連續數值',
    core: '支援向量機尋找能最大化類別間隔的邊界；搭配 kernel 後，可以在高維空間處理非線性分界。',
    workflow: ['標準化特徵尺度', '選擇 linear、poly 或 RBF kernel', '調整 C 與 gamma', '用交叉驗證檢查泛化能力'],
    metrics: ['Accuracy', 'F1-score', 'Margin', 'ROC-AUC'],
    pitfalls: ['對尺度敏感', '大型資料訓練成本高', 'C 與 gamma 不易直覺設定', '機率輸出需額外校準'],
    practice: '把手寫數字影像轉成特徵後，使用 RBF kernel 分類不同數字，並比較標準化前後的表現。',
  },
  5: {
    output: '類別或數值',
    core: 'K 最近鄰不建立明確參數模型，而是在預測時找出距離最近的 K 個樣本，再投票或平均。',
    workflow: ['定義合理距離', '先標準化特徵', '用驗證集選擇 K 值', '檢查高維資料是否造成距離失效'],
    metrics: ['Accuracy', 'F1-score', 'RMSE', '鄰近距離分布'],
    pitfalls: ['預測時需要計算距離，資料大時較慢', '高維度會讓距離變得不可靠', '特徵尺度不一致會扭曲鄰近關係', 'K 太小容易受雜訊影響'],
    practice: '用使用者消費頻率、平均客單價與商品偏好，找出相似顧客並做推薦分群。',
  },
  6: {
    output: '類別機率',
    core: '樸素貝氏使用貝氏定理估計類別機率，並假設特徵在給定類別後彼此條件獨立，因此特別適合文字特徵。',
    workflow: ['把文字轉成詞頻或 TF-IDF 特徵', '選擇 Multinomial、Bernoulli 或 Gaussian 版本', '加入平滑避免零機率', '用混淆矩陣檢查錯誤類別'],
    metrics: ['Accuracy', 'Precision', 'Recall', 'F1-score', 'Confusion matrix'],
    pitfalls: ['特徵獨立假設不一定成立', '高度相關特徵可能被重複計算影響', '訓練資料詞彙不足時泛化差', '罕見詞需要平滑處理'],
    practice: '用新聞內文的詞頻特徵訓練主題分類器，再觀察哪些詞最容易造成誤判。',
  },
  7: {
    output: '群組標籤',
    core: 'K-Means 反覆把資料分到最近的群中心，再更新群中心位置，目標是降低群內點到中心的距離總和。',
    workflow: ['先標準化數值特徵', '用 elbow 或 silhouette 協助選 K', '多次初始化降低局部最小值風險', '用業務語意解讀每個群'],
    metrics: ['Inertia', 'Silhouette score', '群內距離', '群間差異'],
    pitfalls: ['需要事先指定 K', '對初始中心敏感', '不適合非球狀群', '離群值會拉動群中心'],
    practice: '用平均消費、造訪次數與優惠券使用率做顧客分群，命名各群並設計不同行銷策略。',
  },
  8: {
    output: '降維座標',
    core: 'PCA 找出資料變異最大的正交方向，將高維資料投影到少數主成分上，以保留主要資訊並降低維度。',
    workflow: ['先標準化特徵', '檢查解釋變異比例', '選擇主成分數量', '用低維座標視覺化或作為後續模型輸入'],
    metrics: ['Explained variance ratio', '累積解釋變異', '重建誤差'],
    pitfalls: ['主成分不一定容易解釋', '只保留最大變異可能忽略對預測重要的小變異', '非線性結構不一定能用 PCA 保留', '未標準化會讓大尺度特徵主導結果'],
    practice: '將多維顧客特徵投影到 2D，觀察資料是否自然形成群，再搭配 K-Means 做分群。',
  },
  9: {
    output: '類別、數值或生成結果',
    core: '類神經網路由多層神經元組成，透過權重與非線性 activation 學習複雜模式，是深度學習模型的基礎。',
    workflow: ['準備大量且一致的資料', '設計層數、神經元與 activation', '設定 loss、optimizer 與 batch size', '用驗證集監控過擬合'],
    metrics: ['Accuracy', 'Loss curve', 'Validation loss', 'F1-score'],
    pitfalls: ['資料少時容易過擬合', '訓練成本高', '模型較難解釋', '超參數與資料前處理影響很大'],
    practice: '用影像資料訓練簡單多層神經網路或 CNN，觀察訓練曲線與驗證曲線是否分離。',
  },
};

export const reportGuide = {
  modelingFlow: ['問題定義', '資料蒐集', '資料清理', '特徵工程', '訓練/驗證/測試切分', '模型訓練', '模型評估', '解釋與部署維護'],
  evaluationMap: [
    { task: '回歸', metrics: 'MAE、MSE、RMSE、R-squared、殘差圖' },
    { task: '分類', metrics: 'Accuracy、Precision、Recall、F1-score、ROC-AUC、PR-AUC' },
    { task: '分群', metrics: '群內距離、群間差異、Silhouette score、業務可解釋性' },
    { task: '降維', metrics: '解釋變異比例、重建誤差、視覺化合理性、後續任務表現' },
  ],
  selectionRules: [
    '先從簡單模型建立 baseline，再逐步增加複雜度。',
    '模型表現不好時，先檢查資料品質、特徵定義、切分方式與評估指標。',
    '模型表現異常好時，要懷疑資料洩漏或訓練/測試資料重複。',
    '線性模型、SVM、KNN、K-Means、PCA 通常需要標準化；樹模型通常較不依賴尺度。',
  ],
};
